/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB_informationssystem;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author axelh
 */
public class AdminUtrustningJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminUtrustningJFrame
     */
    private InfDB idb;
    
    public AdminUtrustningJFrame() {
        initComponents();
        
        döljNyUtrustning();
        lbTillagd.setVisible(false);
        
           try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel" + ettUndantag);
        }         
    }
    
    private void insertDB(String fraga){
    
        try {
          
            String ettFordon = fraga;
           
            idb.insert(ettFordon);

            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Försök igen");
        } 
    }
    
           
        private void döljNyUtrustning (){
        
       
       ntbOKutrustning.setVisible(false);
        btnVäljUtrustning.setVisible(false);
        
        txtNyEtt.setVisible(false);
        txtNyTvå.setVisible(false);
        txtNyTre.setVisible(false);
        txtNyFyra.setVisible(false);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setVisible(false);
         lbNyTvå.setVisible(false);
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
          
        }
        
        private void cleartxtWindow(){
        
            txtNyEtt.setText("");
            txtNyTvå.setText("");
            txtNyTre.setText("");
            txtNyFyra.setText("");
        
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNyUtrustning = new javax.swing.JButton();
        btnVäljUtrustning = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();
        ntbOKutrustning = new javax.swing.JButton();
        txtNyEtt = new javax.swing.JTextField();
        txtNyTvå = new javax.swing.JTextField();
        txtNyTre = new javax.swing.JTextField();
        txtNyFyra = new javax.swing.JTextField();
        lbNyEtt = new javax.swing.JLabel();
        lbNyTre = new javax.swing.JLabel();
        lbNyTvå = new javax.swing.JLabel();
        lbNyFyra = new javax.swing.JLabel();
        lbTillagd = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNyUtrustning.setText("Ny utrustning");
        btnNyUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyUtrustningActionPerformed(evt);
            }
        });

        btnVäljUtrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Typ", "Utrustning", "Kommunikation", "Fordon", "Teknik", "Vapen" }));
        btnVäljUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVäljUtrustningActionPerformed(evt);
            }
        });

        btnTaBort.setText("Ta bort Utrustning");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        ntbOKutrustning.setText("OK");
        ntbOKutrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntbOKutrustningActionPerformed(evt);
            }
        });

        txtNyEtt.setColumns(8);

        txtNyTvå.setColumns(8);

        txtNyTre.setColumns(8);
        txtNyTre.setText("ÅÅÅÅ-MM-DD");

        txtNyFyra.setColumns(8);

        lbNyFyra.setToolTipText("");

        lbTillagd.setText("Utrustning Tillagd!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTaBort, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(btnNyUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ntbOKutrustning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyTre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNyTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyEtt)
                                .addGap(7, 7, 7)
                                .addComponent(txtNyEtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyFyra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNyFyra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyTvå)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNyTvå, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbTillagd)
                        .addComponent(btnVäljUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(416, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNyUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbTillagd))
                        .addGap(74, 74, 74)
                        .addComponent(btnTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVäljUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ntbOKutrustning)
                            .addComponent(txtNyEtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNyTvå, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNyEtt)
                            .addComponent(lbNyTvå))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNyTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNyFyra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNyTre)
                            .addComponent(lbNyFyra))))
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNyUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyUtrustningActionPerformed
        // Visar min combobox för att välja typ av utrustning
        lbTillagd.setVisible(false);
        btnVäljUtrustning.setVisible(true);
    }//GEN-LAST:event_btnNyUtrustningActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnVäljUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVäljUtrustningActionPerformed
      // TODO add your handling code here:
      
      String utrustning = btnVäljUtrustning.getSelectedItem().toString();
      
      
      if ("Fordon".equals(utrustning)){
      
          //Visar de labels jag vill
          txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(true);
          txtNyFyra.setVisible(true);
          lbNyEtt.setVisible(true);
          lbNyTvå.setVisible(true);
          lbNyTre.setVisible(true);
         lbNyFyra.setVisible(true);
         ntbOKutrustning.setVisible(true);
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Fordons ID:");
         lbNyTvå.setText("Fordonsbeskrivning:");
         lbNyTre.setText("Registreringsdatum:");
         lbNyFyra.setText("Årsmodell:");
         
         
                 
      }
      
      if ("Kommunikation".equals(utrustning)){
          
           //Visar de labels jag vill
          txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(true);
   
          
         // Ger de namnen jag vill och döljer 3 samt 4
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Överforingsteknik:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
         lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
      }
      
      if ("Teknik".equals(utrustning)){
          
           //Visar de labels jag vill
           txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
   ntbOKutrustning.setVisible(true);
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Kraftkalla:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
           lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
         
      }
      
      if ("Utrustning".equals(utrustning)){
          
           //Visar de labels jag vill
           txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(true);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Benämning:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
           lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
         
      }
      
      if ("Vapen".equals(utrustning)){
          
           //Visar de labels jag vill
           txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(true);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Kaliber:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
           lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
      }
      
      if ("Välj Typ".equals(utrustning)) {
       txtNyEtt.setVisible(false);
          txtNyTvå.setVisible(false);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(false);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setVisible(false);
         lbNyTvå.setVisible(false);
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
       
      }
    
    }//GEN-LAST:event_btnVäljUtrustningActionPerformed

    private void ntbOKutrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntbOKutrustningActionPerformed
        // A
        // B Spara varje string
        // C Varje columns värde
        // D insert fråga till databasen
        String utrustning = btnVäljUtrustning.getSelectedItem().toString();
        
        String txtEtt = txtNyEtt.getText();
        String txtTvå = txtNyTvå.getText();
        String txtTre = txtNyTre.getText();
        String txtFyra = txtNyFyra.getText();
        
        
        //TOOO DOO måste sätta en en saka som tar bort texten i ruta tre och fyra om man väljer bort det i comboboxen
      if ("Fordon".equals(utrustning)) {
      
      String input = "INSERT INTO fordon VALUES ('"+ txtEtt +"','"+ txtTvå + "','" + txtTre + "', '" + txtFyra + "');";
      
      JOptionPane.showMessageDialog(null, "frågan  " + input);
      
      insertDB(input);
      
      
      }
      
      if ("Kommunikation".equals(utrustning)) {
      
          String input = "INSERT INTO kommunikation VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
      
      if ("Teknik".equals(utrustning)) {
      
          String input = "INSERT INTO teknik VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
      
      if ("Utrustning".equals(utrustning)) {
      
          String input = "INSERT INTO utrustning VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
           if ("Vapen".equals(utrustning)) {
      
          String input = "INSERT INTO vapen VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
      
      döljNyUtrustning();
      cleartxtWindow();
      lbTillagd.setVisible(true);
      
    }//GEN-LAST:event_ntbOKutrustningActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUtrustningJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNyUtrustning;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> btnVäljUtrustning;
    private javax.swing.JLabel lbNyEtt;
    private javax.swing.JLabel lbNyFyra;
    private javax.swing.JLabel lbNyTre;
    private javax.swing.JLabel lbNyTvå;
    private javax.swing.JLabel lbTillagd;
    private javax.swing.JButton ntbOKutrustning;
    private javax.swing.JTextField txtNyEtt;
    private javax.swing.JTextField txtNyFyra;
    private javax.swing.JTextField txtNyTre;
    private javax.swing.JTextField txtNyTvå;
    // End of variables declaration//GEN-END:variables
}
