/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB_informationssystem;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
/**
 *
 * @author axelh
 */
public class AdminUtrustningJFrame extends javax.swing.JFrame {

    /**
     * Creates new form AdminUtrustningJFrame
     */
    private InfDB idb;
    
    public AdminUtrustningJFrame() {
        initComponents();
        
        döljNyUtrustning();
        lbTillagd.setVisible(false);
        doljTaBort(true);
        
           try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel" + ettUndantag);
        }         
    }
    
    private void skrivUt(String nyRad){
    
    txtLista.setText(txtLista.getText() + nyRad);
    
    }
    
    private void insertDB(String fraga){
    
        try {
          
            String ettFordon = fraga;
           lbTillagd.setVisible(true);
            idb.insert(ettFordon);

            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, "Försök igen");
        } 
    }
    
           
        private void döljNyUtrustning (){
        
       
       ntbOKutrustning.setVisible(false);
        btnVäljUtrustning.setVisible(false);
        
        txtNyEtt.setVisible(false);
        txtNyTvå.setVisible(false);
        txtNyTre.setVisible(false);
        txtNyFyra.setVisible(false);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setVisible(false);
         lbNyTvå.setVisible(false);
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
          
        }
        
        private void cleartxtWindow(){
        
            txtNyEtt.setText("");
            txtNyTvå.setText("");
            txtNyTre.setText("");
            txtNyFyra.setText("");
         
        
        }
        
        private void doljTaBort(boolean tabort){
        
        if (tabort == true)  { 
        txtBortEtt.setVisible(false);
        txtBortTvå.setVisible(false);
        lbBortEtt.setVisible(false);
        lbBortTvå.setVisible(false);
        comboTaBort.setVisible(false);
        btnTaBort.setVisible(false);
        }
        
        else {
        txtBortEtt.setVisible(true);
        txtBortTvå.setVisible(true);
        lbBortEtt.setVisible(true);
        lbBortTvå.setVisible(true);
        comboTaBort.setVisible(true);
        btnTaBort.setVisible(true);
        
        }
            
        
        
        
        
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnNyUtrustning = new javax.swing.JButton();
        btnVäljUtrustning = new javax.swing.JComboBox<>();
        btnStorTaBort = new javax.swing.JButton();
        ntbOKutrustning = new javax.swing.JButton();
        txtNyEtt = new javax.swing.JTextField();
        txtNyTvå = new javax.swing.JTextField();
        txtNyTre = new javax.swing.JTextField();
        txtNyFyra = new javax.swing.JTextField();
        lbNyEtt = new javax.swing.JLabel();
        lbNyTre = new javax.swing.JLabel();
        lbNyTvå = new javax.swing.JLabel();
        lbNyFyra = new javax.swing.JLabel();
        lbTillagd = new javax.swing.JLabel();
        comboTaBort = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();
        txtBortEtt = new javax.swing.JTextField();
        txtBortTvå = new javax.swing.JTextField();
        lbBorttagen = new javax.swing.JLabel();
        lbBortEtt = new javax.swing.JLabel();
        lbBortTvå = new javax.swing.JLabel();
        txtLista = new javax.swing.JTextField();
        txtLista2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNyUtrustning.setText("Ny utrustning");
        btnNyUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNyUtrustningActionPerformed(evt);
            }
        });

        btnVäljUtrustning.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Typ", "Utrustning", "Kommunikation", "Fordon", "Teknik", "Vapen" }));
        btnVäljUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVäljUtrustningActionPerformed(evt);
            }
        });

        btnStorTaBort.setText("Ta bort Utrustning");
        btnStorTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStorTaBortActionPerformed(evt);
            }
        });

        ntbOKutrustning.setText("OK");
        ntbOKutrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ntbOKutrustningActionPerformed(evt);
            }
        });

        txtNyEtt.setColumns(8);

        txtNyTvå.setColumns(8);

        txtNyTre.setColumns(8);
        txtNyTre.setText("ÅÅÅÅ-MM-DD");

        txtNyFyra.setColumns(8);

        lbNyFyra.setToolTipText("");

        lbTillagd.setText("Utrustning Tillagd!");

        comboTaBort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Typ", "Utrustning", "Kommunikation", "Fordon", "Teknik", "Vapen" }));
        comboTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTaBortActionPerformed(evt);
            }
        });

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        txtBortEtt.setColumns(8);

        txtBortTvå.setColumns(8);

        lbBorttagen.setText("Utrustning bort tagen!");

        txtLista.setText("txtLista");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        txtLista2.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnStorTaBort, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(btnNyUtrustning, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ntbOKutrustning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyTre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNyTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyEtt)
                                .addGap(7, 7, 7)
                                .addComponent(txtNyEtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyFyra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNyFyra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbNyTvå)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNyTvå, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lbTillagd)
                        .addComponent(btnVäljUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTaBort)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(53, 53, 53)
                                        .addComponent(lbBorttagen))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lbBortEtt)
                                        .addGap(4, 4, 4)
                                        .addComponent(txtBortEtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(lbBortTvå)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtBortTvå, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtLista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(125, 125, 125)))
                        .addComponent(txtLista, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(comboTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNyUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbTillagd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnVäljUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ntbOKutrustning)
                            .addComponent(txtNyEtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNyTvå, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNyEtt)
                            .addComponent(lbNyTvå))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNyTre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNyFyra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbNyTre)
                            .addComponent(lbNyFyra))))
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStorTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(comboTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtLista, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(lbBorttagen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnTaBort)
                                    .addComponent(txtBortEtt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtBortTvå, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbBortEtt)
                                    .addComponent(lbBortTvå))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                                .addComponent(txtLista2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNyUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNyUtrustningActionPerformed
        // Visar min combobox för att välja typ av utrustning
        lbTillagd.setVisible(false);
        btnVäljUtrustning.setVisible(true);
    }//GEN-LAST:event_btnNyUtrustningActionPerformed

    private void btnStorTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStorTaBortActionPerformed
        // TODO add your handling code here:
        doljTaBort(false);
    }//GEN-LAST:event_btnStorTaBortActionPerformed

    private void btnVäljUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVäljUtrustningActionPerformed
      // TODO add your handling code here:
      
      String utrustning = btnVäljUtrustning.getSelectedItem().toString();
      
      
      if ("Fordon".equals(utrustning)){
      
          //Visar de labels jag vill
          txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(true);
          txtNyFyra.setVisible(true);
          lbNyEtt.setVisible(true);
          lbNyTvå.setVisible(true);
          lbNyTre.setVisible(true);
         lbNyFyra.setVisible(true);
         ntbOKutrustning.setVisible(true);
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Fordons ID:");
         lbNyTvå.setText("Fordonsbeskrivning:");
         lbNyTre.setText("Registreringsdatum:");
         lbNyFyra.setText("Årsmodell:");
         
         
                 
      }
      
      if ("Kommunikation".equals(utrustning)){
          
           //Visar de labels jag vill
          txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(true);
   
          
         // Ger de namnen jag vill och döljer 3 samt 4
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Överforingsteknik:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
         lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
      }
      
      if ("Teknik".equals(utrustning)){
          
           //Visar de labels jag vill
           txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
   ntbOKutrustning.setVisible(true);
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Kraftkalla:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
           lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
         
      }
      
      if ("Utrustning".equals(utrustning)){
          
           //Visar de labels jag vill
           txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(true);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Benämning:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
           lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
         
      }
      
      if ("Vapen".equals(utrustning)){
          
           //Visar de labels jag vill
           txtNyEtt.setVisible(true);
          txtNyTvå.setVisible(true);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(true);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setText("Utrustnings_ID:");
         lbNyTvå.setText("Kaliber:");
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
           lbNyEtt.setVisible(true);
         lbNyTvå.setVisible(true);
      }
      
      if ("Välj Typ".equals(utrustning)) {
       txtNyEtt.setVisible(false);
          txtNyTvå.setVisible(false);
          txtNyTre.setVisible(false);
          txtNyFyra.setVisible(false);
          ntbOKutrustning.setVisible(false);
   
          
         // Ger de namnen jag vill
         lbNyEtt.setVisible(false);
         lbNyTvå.setVisible(false);
         lbNyTre.setVisible(false);
         lbNyFyra.setVisible(false);
       
      }
    
    }//GEN-LAST:event_btnVäljUtrustningActionPerformed

    private void ntbOKutrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ntbOKutrustningActionPerformed
        // A
        // B Spara varje string
        // C Varje columns värde
        // D insert fråga till databasen
        String utrustning = btnVäljUtrustning.getSelectedItem().toString();
        
        String txtEtt = txtNyEtt.getText();
        String txtTvå = txtNyTvå.getText();
        String txtTre = txtNyTre.getText();
        String txtFyra = txtNyFyra.getText();
        
        
        //TOOO DOO måste sätta en en saka som tar bort texten i ruta tre och fyra om man väljer bort det i comboboxen
      if ("Fordon".equals(utrustning)) {
      
      String input = "INSERT INTO fordon VALUES ('"+ txtEtt +"','"+ txtTvå + "','" + txtTre + "', '" + txtFyra + "');";
      
      JOptionPane.showMessageDialog(null, "frågan  " + input);
      
      insertDB(input);
      
      
      }
      
      if ("Kommunikation".equals(utrustning)) {
      
          String input = "INSERT INTO kommunikation VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
      
      if ("Teknik".equals(utrustning)) {
      
          String input = "INSERT INTO teknik VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
      
      if ("Utrustning".equals(utrustning)) {
      
          String input = "INSERT INTO utrustning VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
           if ("Vapen".equals(utrustning)) {
      
          String input = "INSERT INTO vapen VALUES ('"+ txtEtt +"','"+ txtTvå + "');";
          
          insertDB(input);
      
      }
      
      döljNyUtrustning();
      cleartxtWindow();
      
      
    }//GEN-LAST:event_ntbOKutrustningActionPerformed

    private void comboTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTaBortActionPerformed
        // TODO add your handling code here:
        String utrustning = comboTaBort.getSelectedItem().toString();
        
         if ("Fordon".equals(utrustning)) {
             lbBortEtt.setText("Fordons ID:");
             
             //ArrayList<String> fraga = new ArrayList<String>();
             
             HashMap<String, String> fraga = new HashMap<String, String>();
           ArrayList<HashMap<String, String>> test = new ArrayList<HashMap<String, String>>();
           
             
             String databasfraga = "SELECT * FROM fordon;";

        try {
            test = idb.fetchRows(databasfraga);
            JOptionPane.showMessageDialog(null, "Fordon " + test);
            //for each loop 
            for (int i = 0; i < test.size(); i++) {
                System.out.println(test.get(i));
                
               String rad = test.get(i).toString();
                
                skrivUt(rad);
                
            }
       
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Något gick fel");

        }
             
        }

        if ("Kommunikation".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }

        if ("Teknik".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }

        if ("Utrustning".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }

        if ("Vapen".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }


        
        
        
    }//GEN-LAST:event_comboTaBortActionPerformed

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // TODO add your handling code here:
        String utrustning = comboTaBort.getSelectedItem().toString();
        
         if ("Fordon".equals(utrustning)) {
             lbBortEtt.setText("Fordons ID:");
             
        }

        if ("Kommunikation".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }

        if ("Teknik".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }

        if ("Utrustning".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }

        if ("Vapen".equals(utrustning)) {
            lbBortEtt.setText("Utrustnings ID:");
        }

    }//GEN-LAST:event_btnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminUtrustningJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminUtrustningJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNyUtrustning;
    private javax.swing.JButton btnStorTaBort;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> btnVäljUtrustning;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboTaBort;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lbBortEtt;
    private javax.swing.JLabel lbBortTvå;
    private javax.swing.JLabel lbBorttagen;
    private javax.swing.JLabel lbNyEtt;
    private javax.swing.JLabel lbNyFyra;
    private javax.swing.JLabel lbNyTre;
    private javax.swing.JLabel lbNyTvå;
    private javax.swing.JLabel lbTillagd;
    private javax.swing.JButton ntbOKutrustning;
    private javax.swing.JTextField txtBortEtt;
    private javax.swing.JTextField txtBortTvå;
    private javax.swing.JTextField txtLista;
    private javax.swing.JScrollPane txtLista2;
    private javax.swing.JTextField txtNyEtt;
    private javax.swing.JTextField txtNyFyra;
    private javax.swing.JTextField txtNyTre;
    private javax.swing.JTextField txtNyTvå;
    // End of variables declaration//GEN-END:variables
}
