/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB_informationssystem;

import static java.lang.Integer.parseInt;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author robertkorpics
 */
public class AdminAgentMeny extends javax.swing.JFrame {

    private InfDB idb;
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    /**
     * Creates new form AdminAgentMeny
     */
    public AdminAgentMeny() {
        initComponents();
        
        jPanelRegAgent.setVisible(false);
        jPanelDelAgent.setVisible(false);
        jPanelAlterAgent.setVisible(false);
        jPanelMerInställningar.setVisible(false);

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ettUndantag) {
            JOptionPane.showMessageDialog(null, "Något gick fel" + ettUndantag);
        }
       
        fetchComboBox();
        

    }

    private void fetchComboBox() {

        String fetchOmrade = "SELECT BENAMNING FROM OMRADE";
        ArrayList<String> comboList;
        try {
            System.out.println("x");

            comboList = idb.fetchColumn(fetchOmrade);

            System.out.println(comboList);
            for (String list : comboList) {
                jComboBoxOmrade.addItem(list);
            }
        } catch (InfException ex) {
            System.out.println("y");
            JOptionPane.showMessageDialog(null, "Felmeddelande:" + ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonRegAgent = new javax.swing.JButton();
        jButtonDelAgent = new javax.swing.JButton();
        jButtonAlterAgent = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanelRegAgent = new javax.swing.JPanel();
        jLabelRegAgent = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAgentRegAgentID = new javax.swing.JTextField();
        jTextFieldAgentRegNamn = new javax.swing.JTextField();
        jTextFieldAgentRegTelNr = new javax.swing.JTextField();
        jTextFieldAgentRegPW = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonAgentRegRensa = new javax.swing.JButton();
        jComboBoxAdmin = new javax.swing.JComboBox<>();
        jComboBoxOmrade = new javax.swing.JComboBox<>();
        jTextFieldDatum = new javax.swing.JTextField();
        jPanelDelAgent = new javax.swing.JPanel();
        jLabelDelAgent = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonTaBortAgent = new javax.swing.JButton();
        txtFieldTaBortAgent = new javax.swing.JTextField();
        jLabelFelMeddelande = new javax.swing.JLabel();
        jPanelAlterAgent = new javax.swing.JPanel();
        jLabelAlterAgent = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldRedigeraAgent = new javax.swing.JTextField();
        jComboBoxRedigeraAgent = new javax.swing.JComboBox<>();
        jTxtRedigeraAgent = new javax.swing.JTextField();
        jButtonUppdateraAgent = new javax.swing.JButton();
        jButtonRensaRedigeraAgent = new javax.swing.JButton();
        jPanelMerInställningar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton2 = new javax.swing.JButton();
        jButtonTillbaka = new javax.swing.JButton();
        jButtonMerInställningar = new javax.swing.JButton();

        jButton4.setText("jButton1");

        jTextField3.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonRegAgent.setText("Registrera en Agent");
        jButtonRegAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegAgentActionPerformed(evt);
            }
        });

        jButtonDelAgent.setText("Ta bort Agent");
        jButtonDelAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDelAgentActionPerformed(evt);
            }
        });

        jButtonAlterAgent.setText("Ändra Agent");
        jButtonAlterAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterAgentActionPerformed(evt);
            }
        });

        jLabelRegAgent.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelRegAgent.setText("Agent registrering");
        jLabelRegAgent.setSize(new java.awt.Dimension(45, 20));

        jLabel1.setText("Agent ID");

        jLabel2.setText("Namn");

        jLabel3.setText("Telefon");

        jLabel4.setText("Anställningsdatum");

        jLabel5.setText("Administrator");

        jLabel6.setText("Lösenord");

        jLabel7.setText("Område");

        jButton1.setText("Spara");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAgentRegRensa.setText("Rensa");
        jButtonAgentRegRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgentRegRensaActionPerformed(evt);
            }
        });

        jComboBoxAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "J", "N" }));

        javax.swing.GroupLayout jPanelRegAgentLayout = new javax.swing.GroupLayout(jPanelRegAgent);
        jPanelRegAgent.setLayout(jPanelRegAgentLayout);
        jPanelRegAgentLayout.setHorizontalGroup(
            jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabelRegAgent))
                    .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonAgentRegRensa))
                            .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                                .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(24, 24, 24)
                                .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldAgentRegTelNr)
                                    .addComponent(jTextFieldAgentRegNamn)
                                    .addComponent(jTextFieldAgentRegAgentID)
                                    .addComponent(jTextFieldAgentRegPW)
                                    .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                                        .addComponent(jComboBoxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 8, Short.MAX_VALUE))
                                    .addComponent(jComboBoxOmrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanelRegAgentLayout.setVerticalGroup(
            jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelRegAgent)
                .addGap(18, 18, 18)
                .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAgentRegAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelRegAgentLayout.createSequentialGroup()
                        .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldAgentRegNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3))
                    .addComponent(jTextFieldAgentRegTelNr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRegAgentLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBoxAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldAgentRegPW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jComboBoxOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelRegAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAgentRegRensa)
                            .addComponent(jButton1)))
                    .addComponent(jTextFieldDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        jLabelDelAgent.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelDelAgent.setText("Ta bort Agent");

        jLabel8.setText("Agent namn :");

        jButtonTaBortAgent.setText("Ta bort");
        jButtonTaBortAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTaBortAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelDelAgentLayout = new javax.swing.GroupLayout(jPanelDelAgent);
        jPanelDelAgent.setLayout(jPanelDelAgentLayout);
        jPanelDelAgentLayout.setHorizontalGroup(
            jPanelDelAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDelAgentLayout.createSequentialGroup()
                .addGroup(jPanelDelAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelDelAgentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelFelMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelDelAgentLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanelDelAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelDelAgent)
                            .addGroup(jPanelDelAgentLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelDelAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButtonTaBortAgent)
                                    .addComponent(txtFieldTaBortAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanelDelAgentLayout.setVerticalGroup(
            jPanelDelAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDelAgentLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabelDelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanelDelAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldTaBortAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFelMeddelande, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTaBortAgent)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jLabelAlterAgent.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabelAlterAgent.setText("Redigera Agent");

        jLabel9.setText("Agent ID");

        jComboBoxRedigeraAgent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Namn", "Telefon", "Anställningsdatum", "Administrator", "Losenord", "Område", " " }));

        jButtonUppdateraAgent.setText("Uppdatera");
        jButtonUppdateraAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUppdateraAgentActionPerformed(evt);
            }
        });

        jButtonRensaRedigeraAgent.setText("Rensa");
        jButtonRensaRedigeraAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRensaRedigeraAgentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAlterAgentLayout = new javax.swing.GroupLayout(jPanelAlterAgent);
        jPanelAlterAgent.setLayout(jPanelAlterAgentLayout);
        jPanelAlterAgentLayout.setHorizontalGroup(
            jPanelAlterAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterAgentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAlterAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAlterAgent)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelAlterAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldRedigeraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelAlterAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonRensaRedigeraAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonUppdateraAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTxtRedigeraAgent, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxRedigeraAgent, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanelAlterAgentLayout.setVerticalGroup(
            jPanelAlterAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlterAgentLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabelAlterAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAlterAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldRedigeraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jComboBoxRedigeraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTxtRedigeraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonUppdateraAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRensaRedigeraAgent)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel10.setText("Mer inställningar");

        jLabel11.setText("Agent namn:");

        jCheckBox1.setText("Admin status");

        jCheckBox2.setText("Områdeschef");

        jCheckBox3.setText("Kontorschef");

        jButton2.setText("SPARA");

        javax.swing.GroupLayout jPanelMerInställningarLayout = new javax.swing.GroupLayout(jPanelMerInställningar);
        jPanelMerInställningar.setLayout(jPanelMerInställningarLayout);
        jPanelMerInställningarLayout.setHorizontalGroup(
            jPanelMerInställningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMerInställningarLayout.createSequentialGroup()
                .addGroup(jPanelMerInställningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMerInställningarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMerInställningarLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanelMerInställningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox2)
                            .addComponent(jCheckBox1)
                            .addComponent(jCheckBox3)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanelMerInställningarLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel10)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMerInställningarLayout.setVerticalGroup(
            jPanelMerInställningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMerInställningarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMerInställningarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1))
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLayeredPane1.setLayer(jPanelRegAgent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelDelAgent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelAlterAgent, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanelMerInställningar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelRegAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelMerInställningar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelAlterAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(129, 129, 129))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanelRegAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMerInställningar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addComponent(jPanelDelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelAlterAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
        );

        jButtonTillbaka.setText("Tillbaka");
        jButtonTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTillbakaActionPerformed(evt);
            }
        });

        jButtonMerInställningar.setText("Mer Inställningar");
        jButtonMerInställningar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMerInställningarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAlterAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRegAgent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMerInställningar)
                .addGap(44, 44, 44)
                .addComponent(jButtonTillbaka)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAlterAgent)
                    .addComponent(jButtonDelAgent)
                    .addComponent(jButtonRegAgent)
                    .addComponent(jButtonTillbaka)
                    .addComponent(jButtonMerInställningar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAlterAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterAgentActionPerformed
        // TODO add your handling code here:
        jPanelRegAgent.setVisible(false);
        jPanelDelAgent.setVisible(false);
        jPanelAlterAgent.setVisible(true);
        jPanelMerInställningar.setVisible(false);
    }//GEN-LAST:event_jButtonAlterAgentActionPerformed

    private void jButtonDelAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDelAgentActionPerformed
        // TODO add your handling code here:
        jPanelRegAgent.setVisible(false);
        jPanelDelAgent.setVisible(true);
        jPanelAlterAgent.setVisible(false);
        jPanelMerInställningar.setVisible(false);
    }//GEN-LAST:event_jButtonDelAgentActionPerformed

    private void jButtonRegAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegAgentActionPerformed
        // TODO add your handling code here:
        jPanelRegAgent.setVisible(true);
        jPanelDelAgent.setVisible(false);
        jPanelAlterAgent.setVisible(false);
        jPanelMerInställningar.setVisible(false);
    }//GEN-LAST:event_jButtonRegAgentActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = jTextFieldAgentRegAgentID.getText();
        String datum = jTextFieldDatum.getText();
        String losenord = "'" + jTextFieldAgentRegPW.getText() + "'";
        String namn = "'" + jTextFieldAgentRegNamn.getText() + "'";
        String telefon = "'" + jTextFieldAgentRegTelNr.getText() + "'";
        String omrade = "'" + jComboBoxOmrade.getSelectedItem().toString() + "'";
        String admin = "'" + jComboBoxAdmin.getSelectedItem().toString() + "'";
        SimpleDateFormat format = new SimpleDateFormat("yyyyMMdd");
        Date parsed = null;


        try {
            parsed = format.parse("20110210");
        } catch (ParseException ex) {
            Logger.getLogger(AdminAgentMeny.class.getName()).log(Level.SEVERE, null, ex);
        }
        java.sql.Date sql = new java.sql.Date(parsed.getTime());
        
        int agentID = parseInt(id);
        
        try {
             String omradesID = idb.fetchSingle("Select omrades_id from omrade where benamning = " + omrade);
                String fraga = "INSERT INTO AGENT (AGENT_ID, NAMN, TELEFON, ANSTALLNINGSDATUM, ADMINISTRATOR, LOSENORD, OMRADE) VALUES"
                + " (" + agentID + "," + namn + "," + telefon + "," + datum  + "," + admin + "," + losenord + "," + omradesID + ")";
                System.out.println(fraga);
                idb.insert(fraga);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
             

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonAgentRegRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgentRegRensaActionPerformed
        // TODO add your handling code here:
        jTextFieldAgentRegAgentID.setText("");    
        jTextFieldAgentRegNamn.setText("");
        jTextFieldAgentRegPW.setText("");
        jTextFieldAgentRegTelNr.setText("");
    }//GEN-LAST:event_jButtonAgentRegRensaActionPerformed

    private void jButtonTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTillbakaActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonTillbakaActionPerformed

    private void jButtonTaBortAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTaBortAgentActionPerformed
        String agentNamn = "'" + txtFieldTaBortAgent.getText() + "'";
        String fragaDB = "DELETE FROM AGENT WHERE AGENT.NAMN = " + agentNamn;

        try {
            String agentID = idb.fetchSingle("SELECT AGENT_ID FROM AGENT WHERE NAMN = " + agentNamn);
            String agentAnsvarig = idb.fetchSingle("SELECT ALIEN_ID FROM ALIEN WHERE ANSVARIG_AGENT =" + agentID);
            System.out.println(agentID);
            System.out.println(agentAnsvarig);
            System.out.println(agentNamn);

            if (agentAnsvarig != null) {
                JOptionPane.showMessageDialog(null, "Agenten du försöker ta bort ansvarar över en Alien!");
            } else {
                System.out.println(fragaDB);
                idb.delete(fragaDB);
                txtFieldTaBortAgent.setText("Agent borttagen!");

            }
        } catch (Exception e) {
            System.out.println("catch");

        }


    }//GEN-LAST:event_jButtonTaBortAgentActionPerformed

    private void jButtonRensaRedigeraAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRensaRedigeraAgentActionPerformed
        // Rensar fältet på textfält i redigeraAgent
        jTextFieldRedigeraAgent.setText("");
        jTxtRedigeraAgent.setText("");
    }//GEN-LAST:event_jButtonRensaRedigeraAgentActionPerformed

    private void jButtonMerInställningarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMerInställningarActionPerformed
        // TODO add your handling code here:
        jPanelRegAgent.setVisible(false);
        jPanelDelAgent.setVisible(false);
        jPanelAlterAgent.setVisible(false);
        jPanelMerInställningar.setVisible(true);
    }//GEN-LAST:event_jButtonMerInställningarActionPerformed

    private void jButtonUppdateraAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUppdateraAgentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUppdateraAgentActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminAgentMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminAgentMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminAgentMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminAgentMeny.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminAgentMeny().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButtonAgentRegRensa;
    private javax.swing.JButton jButtonAlterAgent;
    private javax.swing.JButton jButtonDelAgent;
    private javax.swing.JButton jButtonMerInställningar;
    private javax.swing.JButton jButtonRegAgent;
    private javax.swing.JButton jButtonRensaRedigeraAgent;
    private javax.swing.JButton jButtonTaBortAgent;
    private javax.swing.JButton jButtonTillbaka;
    private javax.swing.JButton jButtonUppdateraAgent;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBoxAdmin;
    private javax.swing.JComboBox<String> jComboBoxOmrade;
    private javax.swing.JComboBox<String> jComboBoxRedigeraAgent;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelAlterAgent;
    private javax.swing.JLabel jLabelDelAgent;
    private javax.swing.JLabel jLabelFelMeddelande;
    private javax.swing.JLabel jLabelRegAgent;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelAlterAgent;
    private javax.swing.JPanel jPanelDelAgent;
    private javax.swing.JPanel jPanelMerInställningar;
    private javax.swing.JPanel jPanelRegAgent;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextFieldAgentRegAgentID;
    private javax.swing.JTextField jTextFieldAgentRegNamn;
    private javax.swing.JTextField jTextFieldAgentRegPW;
    private javax.swing.JTextField jTextFieldAgentRegTelNr;
    private javax.swing.JTextField jTextFieldDatum;
    private javax.swing.JTextField jTextFieldRedigeraAgent;
    private javax.swing.JTextField jTxtRedigeraAgent;
    private javax.swing.JTextField txtFieldTaBortAgent;
    // End of variables declaration//GEN-END:variables

}
