/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB_informationssystem;

/**
 *
 * @author adamd
 */
public class TaBortEnAlien extends javax.swing.JFrame {

    /**
     * Creates new form TaBortEnAlien
     */
    public TaBortEnAlien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNamn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTitel = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taFelmeddelanden = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblTitelBild = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setText("Namn");

        lblTitel.setText("Ta bort en Alien");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        jLabel3.setText("Alien ID");

        taFelmeddelanden.setColumns(20);
        taFelmeddelanden.setRows(5);
        jScrollPane1.setViewportView(taFelmeddelanden);

        jLabel4.setText("jLabel3");

        lblTitelBild.setText("jLabel1");

        jLabel6.setText("jLabel3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(32, 32, 32)
                        .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitelBild)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(btnTaBort)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTitel)
                .addGap(40, 40, 40)
                .addComponent(lblTitelBild)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnTaBort)
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // TODO add your handling code here:

        HashMap<String, String> alienInstansData = new HashMap<>();
        ArrayList<String> felmeddelanden = null;
        String felmeddelande = null;
        boolean minstEttFelmeddelande = false;

        if(!Validering.isHeltal(tfID.getText())) {
            felmeddelande = "ID:et behöver vara ett heltal.";
            felmeddelanden.add(felmeddelande);
        }
        else {
            alienInstansData.put("ID", tfID.getText());
        }

        if(!Validering.kollaOmEttNamnArGiltigt(tfNamn.getText()).isEmpty()) {
            felmeddelande = Validering.kollaOmEttNamnArGiltigt(tfNamn.getText());
            felmeddelanden.add(felmeddelande);
        }
        else {
            alienInstansData.put("Namn", tfNamn.getText());
        }

        if(!Validering.kollaEttTelefonnummer(tfTelefonnummer.getText()).isEmpty()) {
            felmeddelande = Validering.kollaEttTelefonnummer(tfTelefonnummer.getText());
            felmeddelanden.add(felmeddelande);
        }
        else {
            alienInstansData.put("Telefonnummer", tfTelefonnummer.getText());
        }

        if(!Validering.platsArRegistrerad(tfPlats.getText()).isEmpty()) {

            felmeddelande = Validering.platsArRegistrerad(tfPlats.getText());
            felmeddelanden.add(felmeddelande);
        }
        else {
            alienInstansData.put("Plats", tfPlats.getText());
        }

        if(!Validering.agentArRegistrerad(tfAgent.getText()).isEmpty()) {

            felmeddelande = Validering.platsArRegistrerad(tfAgent.getText());
            felmeddelanden.add(felmeddelande);
        }
        else {
            alienInstansData.put("Agent", tfAgent.getText());
        }

        if(!Validering.kollaOmLosenordetArGiltigt(tfLosenord.getText()).isEmpty()) {

            felmeddelande = Validering.kollaOmEttDatumArGiltigt(tfLosenord.getText());
            felmeddelanden.add(felmeddelande);
        }
        else {
            alienInstansData.put("Losenord", tfLosenord.getText());
        }

        if(!Validering.kollaOmEttDatumArGiltigt(tfRegistreringsdatum.getText()).isEmpty()) {

            felmeddelande = Validering.kollaOmEttDatumArGiltigt(tfRegistreringsdatum.getText());
            felmeddelanden.add(felmeddelande);
        }
        else {
            alienInstansData.put("Registreringsdatum", tfRegistreringsdatum.getText());
        }

        // Om det finns minst ett felmeddelanden så skrivs det eller de meddelandena ut, annars så registreras utomjordingen i systemet.
        if(felmeddelanden.size() >= 0) {
            String sammanfogadtext = OvrigaFunktioner.sammanfogaText(felmeddelanden);
            taFelmeddelanden.append(sammanfogadtext);
        }
        else {
            alienInstansData = OvrigaFunktioner.trimHashMap(alienInstansData);
            Alienfunktioner.laggTillEnAlien(alienInstansData);
            taFelmeddelanden.append("Registreringen lyckades!");
        }

    }//GEN-LAST:event_btnTaBortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortEnAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaBort;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblTitelBild;
    private javax.swing.JTextArea taFelmeddelanden;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNamn;
    // End of variables declaration//GEN-END:variables
}
