/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MIB_informationssystem;

import java.util.ArrayList;
import java.util.HashMap;

/**
 *
 * @author adamd
 */
public class TaBortEnAlien extends javax.swing.JFrame {

    /**
     * Creates new form TaBortEnAlien
     */
    public TaBortEnAlien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfNamn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblTitel = new javax.swing.JLabel();
        btnTaBort = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taInstansData = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        lblTitelBild = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblFelmeddelandeNamn = new javax.swing.JLabel();
        lblFelmeddelandeID = new javax.swing.JLabel();
        lblMeddelandeTaBort = new javax.swing.JLabel();
        btnSok = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNamnActionPerformed(evt);
            }
        });

        jLabel5.setText("Namn");

        lblTitel.setText("Ta bort en Alien");

        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        jLabel3.setText("Alien ID");

        tfID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfIDActionPerformed(evt);
            }
        });

        taInstansData.setColumns(20);
        taInstansData.setRows(5);
        jScrollPane1.setViewportView(taInstansData);

        jLabel4.setText("jLabel3");

        lblTitelBild.setText("jLabel1");

        jLabel6.setText("jLabel3");

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(345, 345, 345))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblFelmeddelandeNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfID)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnTaBort)
                                    .addComponent(btnSok, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(25, 25, 25)
                                .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMeddelandeTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFelmeddelandeID, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(47, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitelBild)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(lblTitel)
                .addGap(40, 40, 40)
                .addComponent(lblTitelBild)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(lblMeddelandeTaBort, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFelmeddelandeID, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(tfNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(btnSok))
                        .addGap(18, 18, 18)
                        .addComponent(lblFelmeddelandeNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(btnTaBort))
                        .addGap(157, 157, 157))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        // TODO add your handling code here:
        
        if(tfID.getText().isEmpty()) {
            String felmeddelande = "Skriv in ett alien-ID.";
            lblFelmeddelandeID.setText(felmeddelande);
        }
        else {
            
            if(!Validering.isHeltal(tfID.getText())) {
                String felmeddelande = "Skriv in ett heltal i alien-ID-inmatningsfönstret.";
                lblFelmeddelandeID.setText(felmeddelande);
            }
             else {
                AlienFunktioner.taBortEnAlien(tfID.getText());

                if(!AlienFunktioner.taBortEnAlien(tfID.getText()).isEmpty()) {
                    uppdateraTextArean(tfNamn.getText());
                    String meddelande = AlienFunktioner.taBortEnAlien(tfID.getText());
                    lblMeddelandeTaBort.setText(meddelande);
                }
            }
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void tfIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfIDActionPerformed
        // TODO add your handling code here:
        
        
        if(tfID.getText().isEmpty()) {
            String felmeddelande = "Skriv in ett alien-ID.";
            lblFelmeddelandeID.setText(felmeddelande);
        }
        else {
            
            if(!Validering.isHeltal(tfID.getText())) {
                String felmeddelande = "Skriv in ett heltal.";
                lblFelmeddelandeID.setText(felmeddelande);
            }
             else {
                
                HashMap<String, String> alienInstansData = AlienFunktioner.getAlienInstans(tfID.getText(), "Alien_ID");

                ArrayList<String> alienInstansDataArrayList = OvrigaFunktioner.HashMapToArrayList(alienInstansData);

                String alienInstansDataString = OvrigaFunktioner.ArrayListToString(alienInstansDataArrayList);
                
                taInstansData.setText(alienInstansDataString);
            }
        }
        
        
    }//GEN-LAST:event_tfIDActionPerformed

    private void tfNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNamnActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfNamnActionPerformed

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        // TODO add your handling code here:
        
        uppdateraTextArean(tfNamn.getText());
        lblMeddelandeTaBort.setText("");
    }//GEN-LAST:event_btnSokActionPerformed

    private void uppdateraTextArean(String namn) {
        
        if(tfNamn.getText().isEmpty()) {
            String felmeddelande = "Skriv in ett namn.";
            lblFelmeddelandeNamn.setText(felmeddelande);
        }
        else {
            
            if(!Validering.kollaOmEttNamnArGiltigt(tfNamn.getText()).isEmpty()) {
                String felmeddelande = Validering.kollaOmEttNamnArGiltigt(tfNamn.getText());
                lblFelmeddelandeNamn.setText(felmeddelande);
            }
            else {
                
                ArrayList<HashMap<String, String>> alienInstanser = AlienFunktioner.getAlienInstanser(tfNamn.getText());

                String sammanfogadtext = OvrigaFunktioner.hashMapArrayListToString(alienInstanser);

                taInstansData.setText(sammanfogadtext);
            }
        }
        
    }
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaBortEnAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TaBortEnAlien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFelmeddelandeID;
    private javax.swing.JLabel lblFelmeddelandeNamn;
    private javax.swing.JLabel lblMeddelandeTaBort;
    private javax.swing.JLabel lblTitel;
    private javax.swing.JLabel lblTitelBild;
    private javax.swing.JTextArea taInstansData;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNamn;
    // End of variables declaration//GEN-END:variables
}
